{{- if and .Values.externalSecrets.enabled (eq .Values.externalSecrets.secretStore.kind "ClusterSecretStore") -}}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.externalSecrets.secretStore.name }}
  labels:
    {{- include "comments-api.labels" . | nindent 4 }}
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.externalSecrets.gcpProjectId | default .Values.gcpProjectId | quote }}
{{- end }}
