apiVersion: v2
name: comments-api
description: Helm chart para a API de Comentários (Desafio Técnico DevOps Sênior)
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - comments-api
  - devops
  - gke
  - kubernetes
maintainers:
  - name: Rafael Paraná
    email: rparana@artcoder.com.br
